### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Philipp66904**

### CODE REVIEW

**Comment by Philipp66904** [comment]
Tested in SITL

**Comment by Philipp66904** [comment]
@J0las @J0hn-Lawrence  Please review

**Review by J0las — APPROVED** [review]

**Comment by J0hn-Lawrence** [comment]
Maybe we should mention the reason for this change here once. Correct me if I am wrong. Reason for the change: The FCC's PX4 software does some wonky stuff regarding the Mission Progress leading to unwanted flight maneuvres of our drone, therefore we increased the timeout value to 5s instead of 1s to avoid this behavior in the future.

**Review by J0hn-Lawrence — APPROVED** [review]
Approved

**Comment by Philipp66904** [comment]
> Maybe we should mention the reason for this change here once. Correct me if I am wrong. Reason for the change: The FCC's PX4 software does some wonky stuff regarding the Mission Progress leading to unwanted flight maneuvres of our drone, therefore we increased the timeout value to 5s instead of 1s to avoid this behavior in the future.

The problem is the same we had before: After starting a mission through MavSDK, the mission progress sometimes still is `100%` even though it should be `0%`. This is probably a caching problem in MavSDK (@J0las and my guess).
In a first fix (that has been implemented for quite some time and was already flying in the last flight days; see here: https://github.com/THI-Drone/fcc_bridge_package/pull/9) @J0las included a timeout of `1s` after a mission start in which it is assumed that the mission progress is `0%` even though MavSDK might say something different.
In the logs of the last flight day I could see that `1s` isn't enough. The drone started flying to the desired waypoint but stopped after `1s` because the timeout ran out and fcc bridge than assumed that the mission progress of MavSDK (which was `100%`) is correct, even though it wasn't (we need way more time than `1s` to reach our waypoint).
We therefore now changed the timeout delay from `1s` to `5s` in this PR and hope that this fixes the problem.

If the problem still persists, we need to write our own function that calculates the mission progress based on the current location and our target location.

**Pull request merged**
